name: Scorecards analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '21 6 * * 1'
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for uploading to code-scanning dashboard
      id-token: write # for signing results
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: "Run analysis"
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
        with:
          results_file: results.sarif
          # sarif format required by upload-sarif action
          results_format: sarif
          # "repo_token" not set because personal access tokens are dangerous.
          # This means Branch-Protection check will not have correct results.
          publish_results: true

      - name: "Upload to code-scanning dashboard"
        uses: github/codeql-action/upload-sarif@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2.21.7
        with:
          sarif_file: results.sarif
