name: Scorecards analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '21 6 * * 1'
  push:
    branches: [ develop ]
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # for uploading to code-scanning dashboard
      id-token: write # for signing results
      actions: read
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: "Run analysis"
        uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031
        with:
          results_file: results.sarif
          # sarif format required by upload-sarif action
          results_format: sarif
          # "repo_token" not set because personal access tokens are dangerous.
          # This means Branch-Protection check will not have correct results.
          publish_results: true

      - name: "Upload to code-scanning dashboard"
        uses: github/codeql-action/upload-sarif@f6e388ebf0efc915c6c5b165b019ee61a6746a38
        with:
          sarif_file: results.sarif
