on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

name: Specification version check

permissions: {}

jobs:
  # Get the version of the TUF specification the project states it supports
  get-supported-tuf-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v2.3.4
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v2.3.4
        with:
          python-version: "3.x"
      - id: get-version
        run: |
          python3 -m pip install -e .
          script="from tuf.api.metadata import SPECIFICATION_VERSION; \
                  print(f\"v{'.'.join(SPECIFICATION_VERSION)}\")"
          ver=$(python3 -c "$script")
          echo "version=$ver" >> $GITHUB_OUTPUT
  # Get the latest TUF specification release and open an issue (if needed)
  specification-bump-check:
    permissions:
      contents: read
      issues: write
    needs: get-supported-tuf-version
    uses: theupdateframework/specification/.github/workflows/check-latest-spec-version.yml@master # v2.3.4
    with:
      tuf-version: ${{needs.get-supported-tuf-version.outputs.version}}
